# Generated by Django 3.1.7 on 2021-10-02 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('efforts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='parent_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='efforts.team', verbose_name='上级团队'),
        ),
    ]
