# Generated by Django 3.1.7 on 2021-10-05 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('efforts', '0004_auto_20211005_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='effort',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='effort',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
